spring.application.name=fullstack-starter
spring.datasource.url=jdbc:mysql://localhost:3306/fullstack_db
spring.datasource.username=root
spring.datasource.password=9022968375
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
